fix(css): migrate from deprecated css.Sass to resources.ToCSS
Problem
The theme currently uses `css.Sass` function which has been deprecated in Hugo v0.111.0+. 
This causes build failures when using modern Hugo versions:
ERROR: can't evaluate field Sass in type interface {}

Solution
Replace `css.Sass` with `resources.ToCSS` - the official replacement API introduced in Hugo v0.111.0+.